### ISSUE TITLE
rgb(a) issues

### ISSUE THREAD

**Issue by Equals182** [unsyllable/CSS-Color-Marker#4]
Hi!
First of all, it's really useful - thanks for that.
Second, there's a bug. Check out screenshot to see what I'm talking about.

![Check it](https://cloud.githubusercontent.com/assets/4254803/11852944/072e61dc-a44c-11e5-9e34-fb05e76cd2dc.PNG)

Please let me know if you need some additional information.

**Comment by ramiraza** [comment]
Hello,

Thank you for the feedback. I'll try to fix it ASAP and will inform you once it's done. Please stand by. Once again thank you

Regards,
Ali

**Comment by Equals182** [comment]
Ok, thanks :+1:

**Comment by Jacob-Gray** [comment]
Note, there is also a problem with `rgba()` if you accidentally move the Alpha value to the next line like:

```
rgba(0,0,0,
0);
```

It hides all the code(and line numbers. In fact, it hides everything in the currently rendered CodeMirror.
![capture](https://cloud.githubusercontent.com/assets/8271295/12064969/68d646f0-af9d-11e5-916b-9806ef9f30ae.PNG)
![capture2](https://cloud.githubusercontent.com/assets/8271295/12064974/6e94cbde-af9d-11e5-919f-2205a5741e5b.PNG)

**Comment by anephew** [comment]
Hello!

> commented on Dec 17, 2015
> I'll try to fix it ASAP and will inform you once it's done. Please stand by. Once again thank you

Any news on bugfix after 2 months? Unable to use ext with rgba bug
tnx

**Comment by anephew** [comment]
Any news? Work stopped?

**Comment by Jacob-Gray** [comment]
@anephew If he hasn't fixed it soon, I'll fix it, since I am finding it pretty annoying.

**Comment by ramiraza** [comment]
@Jacob-Gray @anephew @Equals182 Sorry guys, I've been busy due to my day job. Unfortunately I haven't had a chance to look into it. Feel free to play around with the .js file, you can do it by messing with the css properties. Once again my apologies.

**Comment by Taraflex** [comment]
@Jacob-Gray @anephew @Equals182
Try original version extension. It must correct works in the Brackets 1.5+ (I hope)
https://github.com/Taraflex/Brackets-Color-Highlighter

**Comment by El4a** [comment]
so still nobody looked into this? =(

**Comment by ramiraza** [comment]
@El4a Hey I'm sorry. I've been brushing up my skills, I'm a fairly new developer so I might not be able to troubleshoot it myself. Feel free to poke at it, if I find a solution, I'll definitely update the repo. Sorry
